---
# Should not be changed
project_uid: "company/project"
workserver_uid: "workserver"
workserver:
    home_dir: "/opt/{{ project_uid }}/{{ workserver_uid }}"
    log_dir: "/var/log/{{ project_uid }}/{{ workserver_uid }}"
